name: mafia_god
description: An Android app for managing Mafia games

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  numberpicker: ^1.1.0

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6+1
  flutter_launcher_icons: ^0.7.4
  flutter_svg: any
  stop_watch_timer: ^0.2.0+2
  circle_wave_progress: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/icon.png
  image_path_android: assets/icon.png
  adaptive_icon_background: assets/background.png
  adaptive_icon_foreground: assets/foreground.png
